In [76]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [77]:
df=pd.read_csv('datasets/CarPrice_Assignment.csv')
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [78]:
df.shape

(205, 26)

In [79]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [80]:
df.drop(['car_ID', 'symboling', 'CarName'],axis=1,inplace=True)

In [81]:
df=pd.get_dummies(df)
df.shape

(205, 52)

In [82]:
X = df.drop('price',axis=1)
Y = df['price']

In [83]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2)

In [84]:
x_train.shape, x_test.shape

((164, 51), (41, 51))

In [85]:
model = LinearRegression().fit(x_train,y_train)

In [86]:
Training_score = model.score(x_train, y_train)
Training_score

0.9312206588169606

In [87]:
y_pred = model.predict(x_test)
y_pred

array([ 6265.10295486,  6912.33452782, 10989.30653398, 14027.3635266 ,
        8123.53530938,  6000.02018271, 28147.21256912,  6832.02817473,
       14424.16374307, 34066.45072659, 10600.78473857, 13578.82368678,
        5910.55941434, 13327.57857973, 11822.88250305, 18495.25976675,
       32429.98192257,  6951.72673808,  7122.46555776, 10886.76556122,
       16070.81313675,  5776.74111859, 10153.56482616, 25785.09437154,
        1731.68695438,  6848.70836733,  6476.97623208,  7463.79931218,
       10615.79287555, 10844.88933511, 30443.00569116,  6281.03210765,
       12388.85487701, 19098.06413014, 37379.68220144, 12567.31666523,
       39580.55247725, 16446.95127655, 11418.87295648, 12788.33873156,
        6447.80327924])

In [88]:
Testing_score = r2_score(y_test, y_pred)
Testing_score

0.9353244064226321

In [89]:
import json

In [90]:
model.coef_

array([ 2.50598450e+01, -4.47220985e+01,  6.31653538e+02,  4.44417732e+01,
        4.77459130e+00,  9.86308936e+01, -1.50081370e+03, -3.56838816e+03,
       -7.38737145e+02, -1.88371142e+00,  2.47403641e+00, -1.55771972e+02,
        1.01865481e+02,  3.92384165e+03, -3.92384165e+03, -6.99688372e+02,
        6.99688372e+02, -1.74905510e+02,  1.74905510e+02,  3.03555103e+03,
       -1.45040311e+03, -7.55116655e+02,  1.29171035e+02, -9.59202300e+02,
       -7.78817737e+02, -5.48826914e+01,  8.33700428e+02, -3.61304395e+03,
        3.61304395e+03,  2.15430963e+02, -3.48291212e+03,  6.36064174e+01,
        4.31231102e+03,  3.07980206e+03, -4.93407495e+03,  7.45836615e+02,
        4.94889819e+03, -4.51719033e+03, -4.94509779e+03, -4.70832031e+02,
        5.66110371e+03, -1.42271836e+03,  7.45836615e+02,  1.06010259e+02,
        8.64736839e+02,  7.45836615e+02,  3.92384165e+03, -3.14400389e+03,
        2.67167606e+02, -2.76358907e+03,  0.00000000e+00])

In [91]:
model.intercept_

-30453.036828113938

In [92]:
model_param = {}
model_param['coef']=list(model.coef_)
model_param['intercept']=model.intercept_.tolist()

In [93]:
json_txt = json.dumps(model_param, indent =4)
json_txt

'{\n    "coef": [\n        25.059845045920593,\n        -44.72209854948139,\n        631.6535375687339,\n        44.44177320367711,\n        4.774591295558906,\n        98.63089355010524,\n        -1500.8136973753326,\n        -3568.38815721216,\n        -738.7371452044437,\n        -1.8837114195394085,\n        2.474036407070567,\n        -155.7719720287728,\n        101.86548074053209,\n        3923.841646646546,\n        -3923.8416466465546,\n        -699.6883724750752,\n        699.688372475101,\n        -174.90550986376692,\n        174.90550986377298,\n        3035.5510287846955,\n        -1450.4031090632013,\n        -755.1166545524227,\n        129.17103488171497,\n        -959.2023000507884,\n        -778.8177370668368,\n        -54.88269142187882,\n        833.700428488737,\n        -3613.0439541293795,\n        3613.0439541293727,\n        215.43096346862868,\n        -3482.9121175130635,\n        63.606417429890215,\n        4312.3110159150165,\n        3079.8020581655783,\

In [94]:
with open ('models/regressor_param.txt', 'w') as file:
    file.write(json_txt)

In [95]:
with open ('models/regressor_param.txt', 'r') as file:
    json_text = json.load(file)

In [96]:
json_model = LinearRegression()

In [97]:
json_model.coef_ = np.array(json_text['coef'])
json_model.intercept_ = np.array(json_text['intercept'])

In [98]:
y_pred = json_model.predict(x_test)
r2_score(y_test, y_pred)

0.9353244064226321

In [99]:
Testing_score

0.9353244064226321

# pickle

In [100]:
import pickle

In [101]:
pickle.dump(model, open('models/model.pkl','wb'))

In [102]:
pickle_model = pickle.load( open('models/model.pkl','rb'))

In [103]:
y_pred=pickle_model.predict(x_test)
y_pred

array([ 6265.10295486,  6912.33452782, 10989.30653398, 14027.3635266 ,
        8123.53530938,  6000.02018271, 28147.21256912,  6832.02817473,
       14424.16374307, 34066.45072659, 10600.78473857, 13578.82368678,
        5910.55941434, 13327.57857973, 11822.88250305, 18495.25976675,
       32429.98192257,  6951.72673808,  7122.46555776, 10886.76556122,
       16070.81313675,  5776.74111859, 10153.56482616, 25785.09437154,
        1731.68695438,  6848.70836733,  6476.97623208,  7463.79931218,
       10615.79287555, 10844.88933511, 30443.00569116,  6281.03210765,
       12388.85487701, 19098.06413014, 37379.68220144, 12567.31666523,
       39580.55247725, 16446.95127655, 11418.87295648, 12788.33873156,
        6447.80327924])

In [104]:
r2_score(y_test,y_pred), Training_score

(0.9353244064226321, 0.9312206588169606)

# Joblib

In [105]:
import joblib

In [106]:
filename='models/model.joblib'

In [107]:
joblib.dump(model,filename)

['models/model.joblib']

In [108]:
joblib_model = joblib.load(filename)

In [109]:
y_pred = joblib_model.predict(x_test)
y_pred

array([ 6265.10295486,  6912.33452782, 10989.30653398, 14027.3635266 ,
        8123.53530938,  6000.02018271, 28147.21256912,  6832.02817473,
       14424.16374307, 34066.45072659, 10600.78473857, 13578.82368678,
        5910.55941434, 13327.57857973, 11822.88250305, 18495.25976675,
       32429.98192257,  6951.72673808,  7122.46555776, 10886.76556122,
       16070.81313675,  5776.74111859, 10153.56482616, 25785.09437154,
        1731.68695438,  6848.70836733,  6476.97623208,  7463.79931218,
       10615.79287555, 10844.88933511, 30443.00569116,  6281.03210765,
       12388.85487701, 19098.06413014, 37379.68220144, 12567.31666523,
       39580.55247725, 16446.95127655, 11418.87295648, 12788.33873156,
        6447.80327924])

In [110]:
r2_score(y_test,y_pred), Training_score

(0.9353244064226321, 0.9312206588169606)